spring.application.name=CardGame
spring.datasource.url=jdbc:mysql://localhost:3306/USER_APP
domain.datasource.driver-class=com.mysql.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=password
server.servlet.context-path=/api

security.jwt.secret-key=9e1cdea55a6add8dc6688fbabfd6dd28b1b7896fa39aa36a0bef8f5e6c06c680
# 1h in millisecond
security.jwt.expiration-time=3600000

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG