spring.application.name=CardGame
spring.datasource.url=jdbc:mysql://mysqlDatabase:3306/USER_APP
domain.datasource.driver-class=com.mysql.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=password
